### ISSUE TITLE
ok now this is an important one crash on startup very important cus we are creating a modpack please respond soon!

### ISSUE THREAD

**Issue by Nick-77ab2** [Flaxbeard/Thaumic_Exploration#14]
duplicate enchantment id: version of crash 1.0-2 on jenkins worked yesterday crashed today no changes will try to see if it happens again after deleting config

Exception in server tick loop

java.lang.IllegalArgumentException: Duplicate enchantment id!
    at net.minecraft.enchantment.Enchantment.<init>(Enchantment.java:52)
    at flaxbeard.thaumicexploration.enchantment.EnchantmentBinding.<init>(EnchantmentBinding.java:15)
    at flaxbeard.thaumicexploration.ThaumicExploration.load(ThaumicExploration.java:502)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:513)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:208)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:187)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:314)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:690)
    at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
    at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:318)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:259)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:604)
    at java.lang.Thread.run(Unknown Source)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_55, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 2516616600 bytes (2400 MB) / 3337617408 bytes (3183 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 3 total; -Xms3072M -Xmx4096M -XX:MaxPermSize=1536M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.03 FML v7.2.217.1147 Minecraft Forge 10.12.2.1147 133 mods loaded, 133 mods active
    mcp{9.03} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{7.2.217.1147} [Forge Mod Loader](cauldron1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{10.12.2.1147} [Minecraft Forge](cauldron1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics2-Core{rv0-stable-9} [AppliedEnergistics2 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997Core{1.0.2.4} [Aroma1997Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{1.0.2.12} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MCVanillaTweaks{1.0} [Mariculture - Vanilla Tweaks](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct-Preloader{0.1.1} [Tinkers Corestruct](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    battlegear2{1.0.5.5} [Mine & Blade Battlegear 2 - Bullseye](1.7.2-MB_Battlegear2-Bullseye-1.0.5.5 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.1.484-experimental} [IndustrialCraft 2](industrialcraft-2-2.1.484-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ImmibisCore{58.1.4} [Immibis Core](immibis-core-58.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedRepulsionSystems{58.1.1} [Advanced Repulsion Systems](adv-repulsion-systems-58.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedMachines{58.2.0} [Advanced Machines](advanced-machines-58.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    advancedgenetics{1.5.6} [Advanced Genetics](advancedgenetics-1.5.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AdvancedSolarPanel{1.7.2-3.5.0} [Advanced Solar Panels](AdvancedSolarPanel-1.7.2-3.5.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{6.0.16} [BuildCraft](buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    appliedenergistics2{rv0-stable-9} [Applied Energistics 2](appliedenergistics2-rv0-stable-9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ae2tech{1.0-b73} [AE2 Tech Add-On](AE2TechAddOn-1.7.10-1.0-b73-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    aquaticabyss{1.1.0} [Aquatic Abyss](AquaticAbyss-1.7.2-1.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997CoreHelper{1.0.2.4} [Aroma1997Core|Helper](Aroma1997Core-1.7.2-1.0.2.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AWWayofTime{v1.0.2} [Blood Magic: Alchemical Wizardry](Blood Magic-v1.1.0%281.7.2%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Baubles{1.0.0.16} [Baubles](Baubles-1.7.2-1.0.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.1.1.14} [Thaumcraft](Thaumcraft-1.7.2-4.1.1.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.1.0.289} [Forge Multipart](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{2.4-152} [Thaumic Tinkerer](ThaumicTinkerer-2.4-152.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForbiddenMagic{0.41b} [Forbidden Magic](Forbidden Magic-1.7.2-0.41b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Automagy{0.4.1} [Automagy](Automagy-1.7.2-0.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Backpack{2.0.0} [Backpack](backpack-2.0.0-1.7.x.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BaMsGRAVE{1.4.2_01} [BaM's Grave](bamsgrave-1.7.2-1.4.2_01.jar) Unloaded->Constructed->Pre-initialized->Initialized
    beardedpotato{1.0} [Bearded Potato](beardedpotato-1.0-2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioCraft{1.7.5} [BiblioCraft](BiblioCraft[v1.7.5][MC1.7.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mantle{1.7.2-132.45b0b50} [Mantle](Mantle-1.7.2-0.2.8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.2.0} [Natura](natura-1.7.2-2.2.0a3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{2.0.2} [Biomes O' Plenty](BiomesOPlenty-1.7.2-2.0.2.934-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsBoP{1.6} [BiblioWoods Biomes O'Plenty Edition](BiblioWoods[BiomesOPlenty][v1.6].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{2.4.1.28} [Forestry for Minecraft](forestry_1.7.2-2.4.1.28.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsForestry{1.4} [BiblioWoods Forestry Edition](BiblioWoods[Forestry][v1.4].jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiblioWoodsNatura{1.2} [BiblioWoods Natura Edition](BiblioWoods[Natura][v1.2].jar) Unloaded->Constructed->Pre-initialized->Initialized
    Botania{r1.1-96} [Botania](Botania r1.1-96.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{6.0.16} [BC Builders](buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{6.0.16} [BC Energy](buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{6.0.16} [BC Factory](buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{6.0.16} [BC Transport](buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{6.0.16} [BC Silicon](buildcraft-6.0.16.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildTech{1.7.10_R-1.0.1} [BuildTech](BuildTech-1.7.10-R1.0.1 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    camosuits{1.0.6} [Camo Suits](Camo Suits-1.7.2-1.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CarpentersBlocks{3.2.5} [Carpenter's Blocks](Carpenter's Blocks v3.2.5 - MC 1.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    chisel{1.5.4g} [Chisel](Chisel-1.7.2-1.5.4g.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CompactSolars{4.4.32.311} [Compact Solar Arrays](CompactSolars-1.7.2-4.4.32.311-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CompactWindmills{1.0.3.1} [CompactWindmills](CompactWindmills-1.7.2-1.0.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CoroAI{v1.0} [CoroAI](CoroUtil-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtendedRenderer{v1.0} [Extended Renderer](CoroUtil-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ConfigMod{v1.0} [Extended Mod Config](CoroUtil-1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    cwm{0.8.0-ic2exp} [CompactWaterMills](cwm-172-0.8.0-ic2exp.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DeathCounter{3.0.1} [DeathCounter](DeathCounter-3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    props{1.10} [Decocraft](Decocraft-1.10_1.7.2and1.7.10.jar.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Electro-MagicTools{1.1.2} [Electro-MagicTools](ElectroMagicTools-1.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    tntland{1.0} [Elemental-Power](Elemental-Power-[1.7.2]-1.3 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Enchiridion{1.2a} [Enchiridion](Enchiridion-1.7.X-1.2a.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{2.0_beta} [Ender IO](enderio-2.0_beta.123.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderStorage{1.4.4.8} [EnderStorage](EnderStorage-1.7.2-1.4.4.8-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    extracells{2.1.3} [ExtraCells](ExtraCells-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{1.1.0b} [Extra Utilities](extrautilities-1.1.0b.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.notify{1.0} [Factorization Notification System](Factorization-1.7.2-0.8.82 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization{1.7.2-0.8.82} [Factorization](Factorization-1.7.2-0.8.82 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.misc{1.7.2-0.8.82} [Factorization Miscellaneous Nonsense](Factorization-1.7.2-0.8.82 %281%29.jar) Unloaded->Constructed->Pre-initialized->Initialized
    guilib{1.0.7.2} [GUI Library](Forge_GuiLibv1.0.7.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    GalacticraftCore{3.0.0} [Galacticraft Core](GalacticraftCore-BETA-1.7-3.0.0.150.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GalacticraftMars{3.0.0} [Galacticraft Planets](Galacticraft-Planets-BETA-1.7-3.0.0.150.jar) Unloaded->Constructed->Pre-initialized->Initialized
    GraviSuite{1.7.2-1.9.9c} [Graviation Suite](GraviSuite-1.7.2-1.9.9c.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{9.1.0.0} [Railcraft](Railcraft_1.7.2-9.1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gregtech{MC172} [GregTech](gregtech-1.7-5.03g.jar) Unloaded->Constructed->Pre-initialized->Initialized
    gregarmor{1.0.2} [GregArmor](gregarmor-1.0.2-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    iChunUtil{3.3.0} [iChunUtil](iChunUtil-3.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Hats{3.0.1} [Hats](Hats-3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2NuclearControl{1.7.2.05} [Nuclear Control](ic2nc-1.7.2-1.7.2.05.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ihl{0.493} [IHL Tools & Machines for IC2V2](ihl-tools_n_machines-0.493-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InfiniTubes{58.1.1} [InfiniTubes](infinitubes-58.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-116} [Inventory Tweaks](InventoryTweaks-1.57-116.jar) Unloaded->Constructed->Pre-initialized->Initialized
    iridiummod{0.5} [Iridium Mod](iridiummod-1.7-0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IronChest{6.0.36.725} [Iron Chest](ironchest-1.7.2-6.0.36.725-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Lazy Mod{1.0} [Lazy Mod](LazyMod-1.7.2-1.01.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LiquidXP{58.1.1} [Liquid XP](liquid-xp-58.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    LotsOfFood{1.7.2} [Lots of Food](Lots of Food-1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    lscraft{1.3} [LSCraft](LSCraft_v1.3_mc1.7.2_fml.1121.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.7.2-1.6.0.jenkins478} [Tinkers' Construct](TConstruct-1.7.2-1.6.0.a14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mariculture{b12} [Mariculture](Mariculture-1.7.2-b12.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineTweaker3{1.7.2-3.0.3} [MineTweaker 3](MineTweaker3-1.7.2-3.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MobAmputation{3.0.1} [MobAmputation](MobAmputation-3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morpheus{1.7.2-1.@MINOR.14} [Morpheus](Morpheus-1.7.2-1.5.14.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mystcraft{0.10.15.00} [Mystcraft](mystcraft-1.7.2-0.10.15.00.jar) Unloaded->Constructed->Pre-initialized->Initialized
    mysticaltrinkets{1.4.1} [Mystical Trinkets](MysticalTrinkets-1.4.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NXT's El3ctricity{1.172.2014} [NXT's El3ctricity](NXT_s_El3ctricity-1.172.2014.jar) Unloaded->Constructed->Pre-initialized->Initialized
    bonecraft{1.7.2b} [Pam's BoneCraft](Pam's BoneCraft 1.7.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized
    harvestcraft{1.7.2d} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.2f.zip) Unloaded->Constructed->Pre-initialized->Initialized
    weeeflowers{1.7.2b} [Pam's Weee! Flowers](Pam's WeeeFlowers 1.7.2b.zip) Unloaded->Constructed->Pre-initialized->Initialized
    PneumaticCraft{1.2.1} [PneumaticCraft](PneumaticCraft-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Aroma1997sPortableRecharger{1.0.0.6} [Aroma1997s Portable Recharger](Portable-Recharger-1.7.2-1.0.0.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Core{4.4.4.43} [ProjectRed](ProjectRed-Base-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transmission{4.4.4.43} [ProjectRed-Transmission](ProjectRed-Integration-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Transportation{4.4.4.43} [ProjectRed-Transportation](ProjectRed-Mechanical-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Exploration{4.4.4.43} [ProjectRed-Exploration](ProjectRed-World-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Compatibility{4.4.4.43} [ProjectRed-Compatibility](ProjectRed-Compat-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Integration{4.4.4.43} [ProjectRed-Integration](ProjectRed-Integration-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Illumination{4.4.4.43} [ProjectRed-Illumination](ProjectRed-Lighting-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ProjRed|Expansion{4.4.4.43} [ProjectRed-Expansion](ProjectRed-Mechanical-1.7.2-4.4.4.43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    qCraft{1.2} [qCraft](qCraft1.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    RandomThings{2.1.2} [Random Things](RandomThings-2.1.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RedLogic{58.1.3} [RedLogic](redlogic-58.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    RefinedRelocation{1.0.5e} [Refined Relocation](RefinedRelocation-1.7.2-1.0.5e.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Roguelike{1.3.3} [Roguelike Dungeons](roguelike-1.7.2-1.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    secretroomsmod{@VERSION@} [The SecretRoomsMod](secretroomsmod-1.7.2-4.6.3.365.jar) Unloaded->Constructed->Pre-initialized->Initialized
    spawnercraft{1.0} [SpawnerCraft](SpawnerCraft-1.1.1-mc1.7.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    symcalc{0.13.5} [Symcalc](symcalc-0.13.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    WaslieCore{1.1} [WaslieCore](WaslieCore-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumcraftExtras{1.0} [Thaumcraft Extras 2](ThaumcraftExtras-2-1.0 BETA-1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    thaumcraftgates{1.3.0} [Thaumcraft Gates](ThaumcraftGates-1.3.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects](ThaumcraftMobAspects-1.7.2-2A.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicExploration{0.6.0} [Thaumic Exploration](ThaumicExploration-1.0-2.jar) Unloaded->Constructed->Pre-initialized->Errored
    ti{0.001} [Thaumic Infusion](ThaumicInfusion-0.983.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Torched{3.0.1} [Torched](Torched-3.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TrailMix{3.0.2} [TrailMix](TrailMix-3.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    transmuteLiquids{v1.6} [Transmute Liquids](transmuteliquids-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Tubestuff{58.1.3} [Tubestuff](tubestuff-58.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TWarden{0.0.1} [Thaumic Warden](TWarden-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{2.2.3} [The Twilight Forest](twilightforest-1.7.2-2.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    universalcoins{1.7.2-1.5.3} [Universal Coins](UniversalCoins-1.7.2-1.5.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    witchery{0.20.4} [Witchery](witchery-1.7.2-0.20.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.1.0.289} [Minecraft Multipart Plugin](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MSC2{1.2.1} [Mob Spawn Controls 2](Forge_MSC2v1.2.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.1.0.289} [Forge Microblocks](ForgeMultipart-1.7.2-1.1.0.289-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AE2 Version: stable rv0-stable-9 for Forge 10.12.1.1060
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
    TConstruct Environment: Environment healthy.
    Profiler Position: N/A (disabled)
    Player Count: 0 / 5; []
    Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
    Type: Dedicated Server (map_server.txt)

**Comment by Nick-77ab2** [comment]
yea after config delete still same exact error

**Comment by Nick-77ab2** [comment]
and the version 1.0-2 is the only version i can use with thaumic tinkerer

**Comment by TechnicianLP** [comment]
Cant you read enchantments are saved a an integer (a number) and the number of the enchantment the mod is trying to add is already in use so you have to change the number in config

**Comment by Nick-77ab2** [comment]
i figured that out a long time ago sorry for leaving this up

**Comment by BzrkTheCoder** [comment]
Can someone close this please?

**Comment by Nick-77ab2** [comment]
kk
