### ISSUE TITLE
Crash on start.

### ISSUE THREAD

**Issue by Toaster312** [Flaxbeard/Thaumic_Exploration#4]
Pastebin of crash log located here:
http://pastebin.com/WYXCkuGe
Versions of relevant mods:
Thaumcraft 4.0.5b
Thaumic Tinker 2.1-67
Thaumic Exploration 0.4.4
Forbidden Magic pr0.231

**Comment by Flaxbeard** [comment]
Update Thaumic Tinkerer to the newest version, that will fix the problem.
