### ISSUE TITLE
I don't know what happened?

### ISSUE THREAD

**Issue by Hello25** [Flaxbeard/Thaumic_Exploration#7]
When I am playing this I am trying to get the thinktank and the purified brains but I can't figure out what I am doing wrong. Please reply fast. I already scanned the zombie brain, but that was before I used the mod.

**Comment by Flaxbeard** [comment]
That's a problem with Thaumcraft. Azanor fixed it, but unfortunately, anything scanned prior to the TC4 update doesn't work. nothing I can do :/

**Comment by Hello25** [comment]
Thx, for the info
