### ISSUE TITLE
Idea!

### ISSUE THREAD

**Issue by Hello25** [Flaxbeard/Thaumic_Exploration#8]
Some mods have a way to keep things out over a wide range, like a force field. So why doesn't thaumcraft have them. A force field would keep other bad things out or keep things in. The research could branch off from the wand focus warding, but it should be more dangerous, I think it should require three nether stars and the warding focus in the middle, the rest of the recipe I leave that up to you. Also if it is possible could it have an animation to it like maybe a star that is a block above it shining to indicate that it is on and the star then goes down back into the cube to signify that it is off or does not have enough power. The magical block should also be activated by a redstone signal. As for the power source I don't know. Anyway this is just an idea so do what you want with it and thanks for another great mod to add to thaumcraft to make it mush more enjoyable.

**Comment by Flaxbeard** [comment]
I'll take it into consideration, not sure how hard it would be :)
